### ISSUE TITLE
testing fails randomly

### ISSUE THREAD

**Issue by zJeremiah** [pcelvng/task-tools#160]
These tests seem to fail randomly.  They will work if ran enough times, but this is not ideal. We need to review what may be causing these test failures.

> FAIL: TestDoneTopic (0.00s)

    app_test.go:91: PASS: "task without job"
    app_test.go:91: PASS: "task with job meta"
    app_test.go:91: FAIL: "2 task with job meta" 
          []string{
        - 	"test3:part2\n\tmin: 0s max 0s avg:0s\n\tComplete   1  2020/01/02",
        + 	"test3:part1\n\tmin: 0s max 0s avg:0s\n\tComplete   1  2020/01/02",
        - 	"test3:part1\n\tmin: 0s max 0s avg:0s\n\tComplete   1  2020/01/02",
        + 	"test3:part2\n\tmin: 0s max 0s avg:0s\n\tComplete   1  2020/01/02",
          }

> FAIL: TestReadFiles/skip_invalids (0.00s)

        trial.go:95:   main.out{
            - 	rowCount:  1,
            + 	rowCount:  4,
              	skipCount: 5,
              }

> FAIL: TestApplyRule (0.28s)

    retry_test.go:100: PASS: "no errors - do nothing"
    retry_test.go:100: FAIL: "retry a failed message" 
        
    retry_test.go:100: PASS: "success after 1st retry"
    retry_test.go:100: PASS: "just keeps failing"

> FAIL:` TestReadFiles (0.05s)

    --- FAIL: TestReadFiles/invalid_row (0.01s)
        trial.go:95: should error
    --- FAIL: TestReadFiles/skip_invalids (0.00s)
        trial.go:95: main.out{
              	rowCount:  4,
            - 	skipCount: 1,
            + 	skipCount: 5,
              }

**Comment by jbsmith7741** [comment]
I'm closing as this haven't shown up for a while.
